name: E2E & Build

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

env:
  NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID: ${{ secrets.NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID }}

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  e2e-and-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22.19
      - run: npm ci
      - name: Run E2E Tests
        continue-on-error: true
        run: npm run e2e
      - name: Build for Production
        run: npm run build
      - name: Upload E2E Test Results
        if: always() && !env.ACT
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
